### ISSUE TITLE
The shell doesn't display any error if exec fails

### ISSUE THREAD

**Issue by ecm-pushbx** [FDOS/freecom#1]
The most likely place this should go is at https://github.com/bartoldeman/freecom/blob/master/shell/command.c#L221 This calls into https://github.com/bartoldeman/freecom/blob/master/lib/exec.c which calls into https://github.com/bartoldeman/freecom/blob/master/lib/lowexec.asm

Test case:

```
C:\>ver /r
 
FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
DOS version 7.10
FreeDOS kernel 2042 (build 2042 OEM:0xfd) [compiled May 11 2016]
C:\>type testoom.asm
 
dw "MZ"
times 510 db -1
C:\>nasm testoom.asm -o testoom.exe
C:\>testoom
C:\>
```

Expected: An error message about the program not fitting into memory.

PS please tell me if I should use the other (sf.net) bugtracker instead.

**Comment by bartoldeman** [comment]
Closed by commit 7814502
