### ISSUE TITLE
Version 0.85b

### ISSUE THREAD

**Issue by boeckmann** [FDOS/freecom#100]
Is it ok to make 0.85b from current master? I could then include it in the next FreeDOS interim build.

**Comment by PerditionC** [comment]
yes

**Comment by boeckmann** [comment]
Ok, I managed to build this thing successfully with OpenWatcom 1.9 and could provide binaries for a release. But I can not build it with Turbo C or GCC at the moment. Regarding the FreeDOS package. It has a different structure to that what I get when running buildall.bat. Is it neccessary to have the K-SWAP binaries in the FreeDOS package, or could they be dropped? That would save 1MB.

**Comment by PerditionC** [comment]
Kswap is mostly for 186/8088 computers that lack XMS/extended memory.  The release can omit it if needed and we can add it back for the next release if it turns out to be wanted.  I don't use it myself even on my 8088.

**Comment by boeckmann** [comment]
Now that I missed the merge window for T2406, I think it would be better to postpone 0.85b, until at least #97 and #102 are fixed.

**Comment by PerditionC** [comment]
both bugs are closed, closing this bug as I will be releasing 0.86 in next few days (trying to close a few more bugs first).
