### ISSUE TITLE
support for escaped characters

### ISSUE THREAD

**Issue by codercowboy** [FDOS/freecom#12]
I'd like to see support for escaped characters, particularly in the echo command.

Per [this guide](http://www.robvanderwoude.com/escapechars.php), for example, to display a ">", the usual command would be "echo ^>". 

I'm happy to help. How would I go about adding support for this to the shell? I dug around a little in command.c in an attempt to find the bit of code that handles the ">" for redirection, but didn't find anything super obvious quickly, so a pointer would be helpful.

**Comment by bartoldeman** [comment]
This was a three line change, so I just did it.

**Comment by codercowboy** [comment]
Thanks! To be clear, the resource I linked above lists a few more escapable characters in the table below such as &&, ^^, ^<, ^( and so on. The ">" escaped character is the one I wanted for my uses though, so thanks again!

**Comment by bartoldeman** [comment]
Yes the thing is that it's not necessary for the others since freecom does not support `&`, `&&` etc, so `echo &` already shows an `&`, and `echo ^&` gives `^&`. Then it's just a question which command interpreter you want to be compatible with.

**Comment by codercowboy** [comment]
Ah, good point! Thanks so much for the fix.
