### ISSUE TITLE
Illegal format specifier in string?

### ISSUE THREAD

**Issue by boeckmann** [FDOS/freecom#122]
There is a `(%0)` in one string (all language files). I think this is wrong. At least FreeCOM shows a `?` in that position when printing the string. Maybe we should remove that part of the string, as its purpose is not clear to me.

https://github.com/FDOS/freecom/blob/5e41f37009e622f01a6afbc9d8fab5c068e027f3/strings/DEFAULT.lng#L1391-L1392

**Comment by PerditionC** [comment]
the % needs escaping, it's saying arg 0 i believe

**Comment by PerditionC** [comment]
on my phone,  will verify in a bit

**Comment by boeckmann** [comment]
I also first thought that this might say "arg 0". But I currently fail to see where "arg 0" gets injected. The string is printed by DisplayString, with the string id as its sole argument.

**Comment by ecm-pushbx** [comment]
> I also first thought that this might say "arg 0". But I currently fail to see where "arg 0" gets injected. The string is printed by DisplayString, with the string id as its sole argument.

I think @PerditionC meant it should literally read `%%0` to be displayed as "%0" in the result, as percent-sign zero means "argument 0".

**Comment by boeckmann** [comment]
Ok, got it :)
