### ISSUE TITLE
FreeCOM fails to match any commands in RxDOS 7.24 due to unsupported Int21.6505

### ISSUE THREAD

**Issue by ecm-pushbx** [FDOS/freecom#20]
Tested with "FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]" running on "RxDOS version 7.25 [hg e59148587a27] [2020-01-31]". However, it appears that the current branch head of FreeCOM will be affected too.

(The FreeCOM 0.84-pre7 release's COMMANDG.COM on the same RxDOS kernel version leads to [RxDOSINI's message "Halted. Press Ctrl+Alt+Del to reboot."](https://hg.ulukai.org/ecm/rxdos-7.2x/file/3c5912bf6de3/RxDOS/RxDOSINI.ASM#l3115) which is a separate problem I will explore at another time.)

Interrupt 21h function 6505h (see [RBIL entry](http://www.delorie.com/djgpp/doc/rbinter/id/76/31.html) and its referenced lists in [Format of country information](http://www.delorie.com/djgpp/doc/rbinter/it/50/17.html) and [Format of filename terminator table](http://www.delorie.com/djgpp/doc/rbinter/it/54/17.html)) is not supported in my RxDOS releases yet, and [returns CY set, error 0001h (Invalid function)](https://hg.ulukai.org/ecm/rxdos-7.2x/file/3c5912bf6de3/RxDOS/doscode.asm#l5877).

This appears to lead to [is_fnchar](https://github.com/FDOS/freecom/blob/7ebae2c28731fa1bb1cb84dedf9c36ef4f5b783c/lib/is_fnamc.c#L58) using an uninitialised nlsBuf-derefenced buffer with all zeros. This seems to make [docommand](https://github.com/FDOS/freecom/blob/7ebae2c28731fa1bb1cb84dedf9c36ef4f5b783c/shell/command.c#L342) detect an empty command line. The response "Bad command or filename - "dir"." is given by FreeCOM then.

I will eventually add support for, at least, a default table for function 6505h to RxDOS 7.25, but arguably FreeCOM should default to initialise the buffer itself if the function is not supported.

**Comment by ecm-pushbx** [comment]
For the record, [I fixed the other problem with a kernel bugfix](https://hg.ulukai.org/ecm/rxdos-7.2x/rev/4b35088ba9be). Now, the new version seems to run into the same issue as the older one.

**Comment by PerditionC** [comment]
I believe this should be resolved with cherry picked support for fallback nls values if 650x is unsupported, see commit eb7de78d9764bb5d8abfab1c7414f5e806058502, but I still have to verify.
