### ISSUE TITLE
Typo in the Turkish translation

### ISSUE THREAD

**Issue by cardpuncher** [FDOS/freecom#21]
Hello,

There's a small typo in the Turkish translation:  "code page" was mistakenly translated as "page code" in that language, i.e. what should have been "kod sayfası" was "sayfa kodu". Attached files in the zip archive fix this issue.

You should also probably update the following lines in the files:

"#	Language: English"
"#	Codepage: ASCII (7bit) / any codepage"

Best regards.

[freecom_turkish.zip](https://github.com/FDOS/freecom/files/4583403/freecom_turkish.zip)

**Comment by bitigchi** [comment]
This, and some other errors have been fixed with #23.

**Comment by cardpuncher** [comment]
On 17.05.2020 14:30, Emir Sarı wrote:
> This, and some other errors have been fixed with #23
> <https://github.com/FDOS/freecom/pull/23>.

I checked your corrections and honestly, I think they make the whole
translation much better. I feel kind of weird too, why didn't I think of
these? :-P

I'm going to close this bug report as your pull request should take
precedence.

Thanks a lot Emir.

**Comment by bitigchi** [comment]
No problem, glad to be of help.

**Comment by bitigchi** [comment]
Addendum: I've also translated a bunch of other utilities, @cardpuncher, please feel free to review them as well.
