### ISSUE TITLE
Turkish translation is not used

### ISSUE THREAD

**Issue by bitigchi** [FDOS/freecom#24]
This is a a copy of the issue I've opened before on [SourceForge](https://sourceforge.net/p/freedos/bugs/269/). Basically, after a normal install with Turkish selected, the strings are still in English.

Maybe this bug report belongs to the installer? Can someone advise?

**Comment by PerditionC** [comment]
Sounds like an installation issue, but could just be a missing message set in the released versions of FreeCom.  I will double check.  In a few weeks I plan to post a new release after some testing/stability checks/fixes.  Leave bug open as a reminder.

**Comment by bitigchi** [comment]
Installed RC3. Other utilities except FreeCOM do use Turkish translations, but FreeCOM itself is still in English.

**Comment by bitigchi** [comment]
Tried the Russian installation as well, FreeCOM seems to be displaying Russian text normally. Definitely a problem with the handling of the Turkish localisation.

**Comment by bitigchi** [comment]
@cardpuncher, would you be able to test the RC4 to see if the Turkish translations do show up correctly? I won't be able to test it for a while due to my schedule, but very curious to see if it's okay now. :)

**Comment by cardpuncher** [comment]
On 3.05.2021 22:52, Emir Sarı wrote:
> @cardpuncher <https://github.com/cardpuncher>, would you be able to test
> the RC4 to see if the Turkish translations do show up correctly? I won't
> be able to test it for a while due to my schedule, but very curious to
> see if it's okay now. :)

Unless I did something wrong, I'm afraid the issue still exists. I
installed 1.3RC4 on VirtualBox but when I chose Turkish in the
installer, FreeCOM was still in English after the installation (tested
with a simple DIR /? command) -- whereas other tools like XCOPY were
indeed in Turkish. This is also true for the French language at least.

Pinging @shidel as IMHO he should be aware of this.

**Comment by shidel** [comment]
I'm sorry that the translations for FreeCOM are not yet available and only English has been provided with RC4. 

To the best of my knowledge, there is nothing wrong with the FreeCOM translations. Unfortunately, many of us who work on different aspects of FreeDOS don't communicate directly very often. At present, language translations FreeCOM need to be compiled into the binary. The installer uses your language choice to selectively install a custom version of FreeCOM. 
However, the latest version of FreeCOM was available only in three versions all in English using different compilers. I have just contacted the maintainer of FreeCOM in hopes of getting versions for the different languages. I receive them, I will make them available for testing and include them in the next release.

**Comment by bitigchi** [comment]
Thank you @shidel.

**Comment by PerditionC** [comment]
new release posted, please double check for any issues with the Turkish build; positive or negative results appreciated.  Bug will be closed once new release makes it into the distribution

**Comment by bitigchi** [comment]
How to test this? I presume I have to swap the `command.com` file, is there an easy way to access FDOS VBox hard drive from host machine?

**Comment by bitigchi** [comment]
Thanks @PerditionC. `FREECOM` is now in Turkish.

A bit unrelated, but the keyboard layout selected in Installer does not seem to persist after installation. Is this known behaviour or a bug (@shidel)?

**Comment by shidel** [comment]
@bitigchi Possibly a bug introduced in the new RBE (Release build environment). Could be not formatting or including the data correctly while creating the run-time version of the installer. I'll need to look into it. :-)

**Comment by cardpuncher** [comment]
This seems to be fixed in the latest test build, at least for the Turkish Q keyboard layout.

**Comment by shidel** [comment]
@cardpuncher, good. There was some things regarding keyboard selection that needed fixed. Hopefully, it stays that way. :-)
