### ISSUE TITLE
Useless DIR output with /B option set in the DIRCMD environment variable from autoexec.bat

### ISSUE THREAD

**Issue by cjsthompson** [FDOS/freecom#3]
Hello,

I have stumbled upon a weird bug when trying to set DIRCMD=/W /P /B /ONG in autoexec.bat. When
I do that, if I do DIR (alias ls in the pic) I get a bunch of "String #133" as output instead of the expected list of files:

![screen01](https://user-images.githubusercontent.com/359383/44608172-1f5ed400-a7f3-11e8-82c1-eb55216f5a48.png)
 
If I set DIRCMD in autoexec.bat to "/W /P /B" it works as expected. If I set it to "/W /P /ONG" it works as expected too. But if I set it to "/B /ONG" then I get the "String #133"s again.

If I set DIRCMD from the command line to "/W /P /B /ONG" with the SET command, it works as expected:

Seems like the combination of the options /B and /ONG but only when set from autoexec.bat causes this problem.

This is using "FreeCOM 0.84-pre5 - WATCOMC - XMS_Swap"

**Comment by bartoldeman** [comment]
I'm 99% sure this was fixed in 5c8321f5, as the strings were not copied correctly from XMS if you used "dir /b"; without /b they were working mostly by accident.

**Comment by cjsthompson** [comment]
Thanks. I'll upgrade.
