### ISSUE TITLE
Entering a long command that wraps to a second line breaks history when up-down arrowing through entries

### ISSUE THREAD

**Issue by jsonpittman** [FDOS/freecom#30]
It seems that writing the backspace characters in clrline.c doesn't work properly if the entered command is long enough to wrap to multiple lines. It stop backspacing at the start of the last line. In this example, you can see that once you "up-arrow" through history to the "really long" command, further "up-down arrowing" to shorter commands causes them to not be displayed at the end of the command prompt:

![image](https://user-images.githubusercontent.com/14890626/94757276-666b0c00-035f-11eb-8fff-693de9df4b7b.png)

**Comment by jsonpittman** [comment]
Submitted pull request (#31) with potential fix

**Comment by PerditionC** [comment]
Thanks for the bug report and the fix.
