### ISSUE TITLE
max environment size documentation

### ISSUE THREAD

**Issue by PerditionC** [FDOS/freecom#47]
/E newEnvSize where newEnvSize is a 16bit signed value, docs have 32768 as max value, actual max value per init.c#L440 is 32766.  Find any references and update to actual correct value

**Comment by PerditionC** [comment]
FreeCOM is limited due to use of signed 16bit int during argument parsing to a max value of 32766.  See init.c specifically definition of [optScanInteger](https://github.com/FDOS/freecom/blob/eb7de78d9764bb5d8abfab1c7414f5e806058502/lib/optsi.c#L49:5)
However, per documentation, MS/IBM command.com is documented as having a max value of 32768 (see [Q33449: How to Increase MS-DOS Environment Space](https://jeffpar.github.io/kbarchive/kb/033/Q33449/)) and therefor HTMLHelp command.com documentation (none within this repository documents limit that I could find) also has max value documented as 32768

**Comment by PerditionC** [comment]
So do we change FreeCOM argument processing to support 32768? or do document the limits of FreeCOM and how it is different from MS/PC command.com?

**Comment by PerditionC** [comment]
correction, it is documented in strings\strings\str00c7.c

**Comment by tkchia** [comment]
Hello @PerditionC,

I see that `optScanInteger` does not (need to) process negative integers anyway, so personally I would be more inclined to simply change it to return `unsigned` values --- then we can straightforwardly raise the `/E:` limit to 32,768.

Thank you!

**Comment by PerditionC** [comment]
should be fixed with commit fb23bc0ebafe9b2154d6435d434beffa40caadbd
