### ISSUE TITLE
Fix ci build

### ISSUE THREAD

**Issue by PerditionC** [FDOS/freecom#48]
Fixing bc broke gcc.  Fix it

**Comment by andrewbird** [comment]
So I had a quick look at this and I've done a little tweak that mostly fixes it up. However for some reason the UKR translation has an extra string file which messes up the new makefile now that .objs are explicit mentioned. See
https://github.com/andrewbird/freecom/tree/strings-01.

**Comment by PerditionC** [comment]
Thanks for looking into this.  I'm working on setting up gcc compiler so I can test my changes locally to avoid future breakage

**Comment by andrewbird** [comment]
I'm not sure how others feel about this, but I think that we should switch the build to use Gnu make for all the compilers. At the moment it seems overly complex to use the compiler's native make, as either the use of features must be restricted to the common set, or as in the case of gcc there's the need to translate the watcom one with sed.
Also I didn't grok the need to run the compile twice?
https://github.com/FDOS/freecom/blob/1907de5282f40ea039e44af3f0c3d1bd112ca798/build.bat#L107-L116

**Comment by PerditionC** [comment]
formally freecom used dmake exclusively (it was very hard to find last time I built and it used it many years ago, I actually ended up using an older version because it was all I can find).  My problem with gnu make is I don't have it for Borland and OpenWatcom as a version that works under Windows and DOS, but I'm not against standardizing a single Make version.  This build issue is really annoying - I'm still working on a way to create $(CFG) that works on DOS/Windows and Linux when 2 subdirectories deep e.g. strings\strings vs just strings\; the rule to create it relies on RMFILES which is hardcoded to ..\scripts on DOS/Windows and attempts to use $(TOP)\scripts fails as $(TOP) uses / instead \ which Make doesn't execute properly and attempting to copy ..\$(CFG) into strings\strings isn't working on Linux and $(TOP) can't use $(DIRSEP) because its not defined yet when $(TOP) is defined because $(TOP) is used to include the root configuration makefile.  Anyway I'm stopping for the evening.

**Comment by PerditionC** [comment]
Now to see why ukr has that ff.obj file

**Comment by PerditionC** [comment]
Cleaning up the makefiles to using one version and simplify things is really sounding like a good idea.  We need Bart's opinion though before going down that road

**Comment by andrewbird** [comment]
I'm not that familiar with linking things natively in DOS, so I wonder why in this case we generate many str%04X.c files, then compile them into the corresponding objects, rather than create one .c file and just compile that. Does it change what gets linked somehow?

**Comment by PerditionC** [comment]
Thanks for the fix.  I think the make file needs to be redone otherwise any new or modified strings will break the build again. fixstrs is supposed to create a response file that solved the variable number of strings problem, however, the way it is currently setup that isn't used for the compiling portion, only creation of the lib.  That is a different issue though.  CI build should now be fixed with https://github.com/andrewbird/freecom/commit/26c999c16a1c99f19d7bc21b79b3ee71e04bc394 applied.

**Comment by andrewbird** [comment]
So do you know the reason for the many object files and not just a single one, is it for some optimum linking method?
