### ISSUE TITLE
call incorrectly parsing arguments

### ISSUE THREAD

**Issue by kerravon86** [FDOS/freecom#52]
I am using the latest beta freecom (a couple of days old)
and it is not behaving like MSDOS 5.0 (where the entire
parameter is kept intact). Windows 10 too.

C:\DEVEL\gcc\gcc>type temp.bat
call temp2 ../libiberty/md5.c
C:\DEVEL\gcc\gcc>type temp2.bat
echo %1
C:\DEVEL\gcc\gcc>temp
C:\DEVEL\gcc\gcc>call temp2 ../libiberty/md5.c
C:\DEVEL\gcc\gcc>echo ..
..
C:\DEVEL\gcc\gcc>

**Comment by PerditionC** [comment]
fixed by commit 35028b6b6c825b39193f3b1e806e0f32a21bfb68
