### ISSUE TITLE
Former Todo file

### ISSUE THREAD

**Issue by PerditionC** [FDOS/freecom#53]
From the former TODO file, the below may still need to be done:

- PATH: check if environment functions report errors (in general check errors reported by all internal commands and document them)
- change size of context (? dynamic, bigger, smaller, not sure goal of this)
- Test if "command.com A:\" accepts the A:\command.com (? not sure what this is testing)
- IF: MS DOS 6 says: if a,a==a echo OK!!! (in general check syntax compatibility with MS/PC DOS COMMAND.COM and others such as 4DOS and DR DOS COMMAND.COM)

**Comment by tkchia** [comment]
Hello @PerditionC,

> * Test if "command.com A:" accepts the A:\command.com (? not sure what this is testing)

Apparently MS-DOS 2+ allows a bare path argument which will tell `command.com` where it can reload its transient bits from (and also how to set `COMSPEC`).  It seems that FreeCOM does also have such a feature.

Thank you!

**Comment by PerditionC** [comment]
I have never used it, but yes FreeCom is documented as both supporting passing a path or path and filename which it will then use for comspec (where filename portion is needed if not named command.com) and any resources it needs to load.  If the path is not available, then this argument is ignored.  So I guess this todo item is to verify FreeCom works as documented.  Thanks for directing me to the right area.

**Comment by PerditionC** [comment]
as this issue is now just verify compatibility, closing as that is always a goal/task todo; specific incompatibilities should be opened as specific issues.
