### ISSUE TITLE
European Portuguese

### ISSUE THREAD

**Issue by shidel** [FDOS/freecom#69]
Just a heads up for @andrewbird and @PerditionC ...

New language submission for FreeCOM.

https://github.com/shidel/fd-nls/tree/master/freecom/source

**Comment by andrewbird** [comment]
That's great, but I'm not sure where you got the initial import of Freecom's strings from as the filenames are formed differently, not DOS compliant and at present Freecom's build utilities won't process them.

Freecom's utilities expect `strings/french.{err,lng}`,  your repo has `source/freecom_{err,lng}.fr`. I actually prefer a hybrid of the two, but for now I'll just rename it to `pt.{err,lng}`, or else the utilities will need changes. As we already have a translation called `pt_br.{err,lng}`, what should happen to that?

**Comment by shidel** [comment]
Hi @andrewbird, all of the translation files in [FD-NLS](https://github.com/shidel/fd-nls) came from several places. Sources in packages, the abandoned localization project and developer website. You are more than welcome to rename the ones in FD-NLS and issue a pull request.  The current tool-chain to update the [translation status](https://shidel.github.io/fd-nls/report.html) for programs ignores source files. So, it's not like you'll break anything. :-) 

For the _UTF-8_ versions, just keep the extra `.UTF-8` extension on the end. You'll be ignoring them in the build process anyway. 

**PT_BR**? That is a good question. Honestly, I have know idea. One is _Brazilian_ and the new one is _European_. I don't really know how different they are. After I commit this message, I will forward you the email I received with the _European_ versions. I'm sure they would be happy to answer any of those questions and make any changes to the files you need.

**Comment by andrewbird** [comment]
Ignore question about pt_br, it's cp850/8 and you probably need to import it too

**Comment by shidel** [comment]
I though I had your email, but they are all just responses through notification platforms. Please email me so I can send it to you. My more or less [public email](mailto:jerome@shidel.net) is easy to remember and has really good spam filtering. :-)

**Comment by shidel** [comment]
@andrewbird Wilhelm just provided an update to the [German translation for FreeCOM](https://github.com/shidel/fd-nls/blob/master/freecom/source/freecom_lng.de). I guess there were numerous typos in the previous one.
