### ISSUE TITLE
Testing for the existence of directories is broken

### ISSUE THREAD

**Issue by cjsthompson** [FDOS/freecom#76]
Drive Q: does not exist. Try "IF EXIST Q:\NUL ECHO Hello". Hello is printed when it shouldn't. C:\FOOBAR\ does not exist. Same problem with "IF EXIST C:\FOOBAR\NUL ECHO Hello".

**Comment by andrewbird** [comment]
I just tested the current version in git and things look fine to me.

D: drive exists
X: drive doesn't

```dos
C:\>if exist x:\nul echo hello
C:\>if exist d:\nul echo there
there
C:\>
```

```dos
C:\>mkdir d:\mydir
C:\>
C:\>if exist d:\mydir\nul echo hello
hello
C:\>if exist d:\nodir\nul echo there
C:\>
```
@PerditionC I think we can close this as I think you did some work https://github.com/FDOS/kernel/commit/6ada304ec2e around this before last release and all seems fine now.

**Comment by PerditionC** [comment]
Should be fixed in upcoming releases
