### ISSUE TITLE
LOADFIX foo.bat treats batch file as executable

### ISSUE THREAD

**Issue by ecm-pushbx** [FDOS/freecom#8]
This https://github.com/FDOS/freecom/blob/b2e3151f41967632ee161da3d59810c763a49563/shell/loadhigh.c#L215 calls exec() which is defined in https://github.com/FDOS/freecom/blob/b0e598470a116d5c588e3836c443730cdbe98221/lib/exec.c#L120 and thus batch files are wrongly loaded with Int21.4B as if they were binary executables.

**Comment by bartoldeman** [comment]
Indeed, lh/loadfix need to reject batch files. Done now.
