### ISSUE TITLE
FreeCOM - Source - docs - html - commands - appendix.html

### ISSUE THREAD

**Issue by fritzmueller** [FDOS/freecom#87]
There seems to be bad readable html code in appendix.html in the following sections:

a) batch scripts, section:
....When a batch file is invoked within another batch file, the previous ones
does <EM>not</EM> proceed once the called one terminates, regardless of the
nesting level; this is called <EM>chaining</EM>, one chains to another
program and does not intend to come back. To have a batch script behave
like an external program in this regard, it must be invoke via the
CALL command, e.g.: .....

The following example is not complete in my eyes. And it is almost not readable with an actual Browser.

b) same with section Pipes - examples.
.... EXAMPLES: EXAMPLE: 1 CMD: cmd1 | cmd2 | cmd3
Which is similiar to this sequence:
CMD: cmd1 >%TEMP%\t1 CMD: cmd2 <%TEMP%\t1 >%TEMP%\t2 CMD: DEL %TEMP%\t1 CMD: cmd3 <%TEMP%\t2 CMD: DEL %TEMP%\t2 EXAMPLE: 2 The first and last command can have an input or output redirection respectively, like so: ......

Not very important, but I wanted to send you a short hint.

**Comment by andrewbird** [comment]
Hello @fritzmueller, thanks for the report. The best way to get it to read how you would like is to submit a PR, then there's no guessing as to exactly what the correct should be.

**Comment by fritzmueller** [comment]
Hi Andrew,
I assume PR should mean Private Response, all other translations by Google seem to be nonsense. And I found no way to send you a private response. Have a look at the screenshots and you will see that the browser handles most of the text in one line. If this should be correct, I big your pardon.
The example in section batch exits abrupt, see appendix 02 and 02b.
![appendix01](https://user-images.githubusercontent.com/43041549/206697675-2fe9b014-cd98-43ed-afb1-f0b95c6aec9f.jpg)
![appendix01b](https://user-images.githubusercontent.com/43041549/206697680-2b11f844-6dcf-4c4c-8707-8da9be86b14c.jpg)
![appendix02](https://user-images.githubusercontent.com/43041549/206697683-7dd7a862-30ef-48b6-b9b6-bd4e92d278c9.jpg)
![appendix02b](https://user-images.githubusercontent.com/43041549/206697684-c89363e9-999d-4270-8ba3-5dfde4a7b13d.jpg)

**Comment by fritzmueller** [comment]
Hope you can follow me. Thx for reading.

**Comment by PerditionC** [comment]
I believe in this context PR means pull request.  I will have a look at this report this weekend.  Thanks.

**Comment by fritzmueller** [comment]
Hi,

referring to appendix.html:

the last batch file was okay. My mistake. So please forget this report.

 


I tried to update appendix.html to a version that works in Firefox etc.

 

Main changes:

 


replaced <CMD> by <B> and </CMD> bei </B>
same with <OPT> and </OPT>
same with <ARG> and </ARG> ---> I have no idea why they are inside.

 

replaced < << by &lt;
replaced > >> by &gt;
replaced & by &amp;
replaced % by &percnt;
corrected redireced to redirected

all this should even work with the latest version of htmlhelp (the one that is not yet
published).

 

I have no idea why the original uses CMD, OPT and ARG.

 

Most changes by me were at I/O redirection, Pipes, Batch Scripts,
added a lot of <BR> for line breaks
added a lot of <p> for an empty line to make the text visible.

 

Please check if "CMD:" is really necessary at the batch examples (I think no, but I left them as they were).

 

Maybe some other minor changes that I have forgotten.

 

I beg your pardon, but I am not yet trained in pull requests etc, so I send it directly.

 

Fritz / Wilhelm Spiegl


 

 

Sent: Friday, December 09, 2022 at 1:46 PM
