### ISSUE TITLE
Build Error using Watcom compiler

### ISSUE THREAD

**Issue by joshux** [FDOS/freecom#88]
config.bat is set to: 
set COMPILER=WATCOM

Error message:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/537575/212840662-33342647-a693-4ba3-a6d9-a77feacfe131.png">

**Comment by mulad** [comment]
I should have looked here before continuing to bang my head against this issue yesterday and today. I came to the same solution after hitting the error, swapping the order of the MMODEL variable definition and the !include line from:

```
!include "$(TOP)/config.mak"
MMODEL = $(FIXSTRS_MMODEL)
```

to:
```
MMODEL = $(FIXSTRS_MMODEL)
!include "$(TOP)/config.mak"
```

in the `strings\strings.mak` file. This allows `-mc` to be added into the `watcomc.cfg` file in that directory and override the usual setting:

```
C:\HOME\MIKE\DOWNLOAD\FREECOM\STRINGS>type watcomc.cfg
-os-s-wx
-IC:\DEVEL\OW\h -I..\suppl
-ms -mc
-UDEBUG -DNDEBUG
```

And to make this searchable, the build error message was:
```
C:\DEVEL\OW\BINW\wcc -zq -fo=.obj fixstrs.c -bt=dos @watcomc.cfg
DOS/4GW Protected Mode Run-time  Version 1.97
Copyright (c) Rational Systems, Inc. 1990-1994
fixstrs.c(163): Error! E1091: "This program must be compiled with far data pointers"
Error(E42): Last command making (fixstrs.obj) returned a bad status
Error(E02): Make execution terminated
```
