### ISSUE TITLE
Freecom doesn't support longfilename

### ISSUE THREAD

**Issue by 4Darmygeometry** [FDOS/freecom#92]
When I load doslfn program and use freecom to dir, it doesn't displays longfilename on the right of dir list. but when I use MSDOS 7.10 (Windows 98 kernel) command.com to dir, it displays longfilename on the right of dir list.

**Comment by andrewbird** [comment]
Try `DIR /LFN`.

**Comment by 4Darmygeometry** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by 4Darmygeometry** [comment]
> Try `DIR /LFN`.

Thanks. I hope that dir can support Longfilename by default, without suffix.

**Comment by andrewbird** [comment]
> I hope that dir can support Longfilename by default, without suffix.

You can set your own default (in autoexec.bat) by doing
`set DIRCMD=/LFN`

Then plain `dir` will be automatically promoted to `dir /lfn`

**Comment by 4Darmygeometry** [comment]
Thanks.
